[package]
name = "raylib-ffi"
version = "0.1.0"
authors = ["Evan Pratten <ewpratten@gmail.com>"]
edition = "2021"
description = "<description>"
documentation = "https://docs.rs/raylib-ffi"
readme = "README.md"
homepage = "https://github.com/ewpratten/raylib-ffi"
repository = "https://github.com/ewpratten/raylib-ffi"
license = "GPL-3.0"
keywords = []
categories = []

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]


[build-dependencies]
bindgen = "^0.63.0"
cmake = "^0.1.49"